<?php
/**
 * @file
 * Code for the GSB Feature Seed Research Project Display feature.
 */

include_once 'gsb_feature_seed_research_library_display.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form.
 */
function gsb_feature_seed_research_library_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'seed_research_listing' && $form_state['view']->current_display == 'seed_research_pane') {
    $form['#action'] = '';
    $form['secondary']['done'] = array(
      '#type' => 'submit',
      '#value' => t('Done'),
    );
    $form['secondary']['clear-all'] = array(
      '#type' => 'button',
      '#value' => t('Clear All'),
    );
  }
}